### ISSUE TITLE
docs/tests: add examples of before and after

### ISSUE THREAD

**Issue by tobiasdiez** [tobiasdiez/storybook-vue-addon#2]
https://storybook.js.org/docs/vue/writing-stories/introduction

add them to https://storybook.js.org/docs/svelte/contribute/new-snippets

**Comment by tobiasdiez** [comment]
@JReinhold @IanVS would you guys accept PRs adding the "vue native" story format to the official documentation? A few people are already using the addon, and it seems stable enough for them (there were a few feature requests but no serious bug reports).

**Comment by tobiasdiez** [comment]
@jonniebigodes and @kylegach, any input on this?

**Comment by jonniebigodes** [comment]
@tobiasdiez sorry for the delay in following up with you on this issue, but there were other items that required my attention. I've talked with the team, and before committing to extending the documentation featuring the addon we'd like some additional clarification on what's currently supported by the addon in terms of features (e.g., args, interaction testing with the `play` function, etc.) so that we're aware of what's currently supported and what's not so that we can plan ahead and see how best to start documenting and come up with a plan moving forward in terms of maintenance and contributors willing to help us support it. 

Let me know and we'll go from there.

Hope you have a great day.

Stay safe

**Comment by tobiasdiez** [comment]
No worries, and thanks for looking into this. 

Currently, most of the basic features are implemented. This includes essentially everything in the documentation https://storybook.js.org/docs/vue/writing-stories/introduction, including the play function. Parameters and decorators are not yet supported, but would be straightforward to implement. Args are missing, mostly because they feel a bit awkward from a vue perspective (see eg https://github.com/tobiasdiez/storybook-vue-addon/issues/13 and https://github.com/tobiasdiez/storybook-vue-addon/issues/1). I've started to translate some of the examples in the docs to the "vue native" format, and this can be found at https://640982c419c9697b75bfd8fb-mhfqpmbmbk.chromatic.com. So these features are definitely working, but many other examples would be straightforward to translate - I just haven't found the time yet and wanted to wait for your feedback.

Let me know if you have any other questions!

**Comment by tobiasdiez** [comment]
@jonniebigodes any update on this?
